# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import validation_pb2 as validation__pb2


class ChecksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChecks = channel.unary_unary(
                '/unary.Checks/GetChecks',
                request_serializer=validation__pb2.Message.SerializeToString,
                response_deserializer=validation__pb2.MessageResponse.FromString,
                )


class ChecksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChecks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChecksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChecks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChecks,
                    request_deserializer=validation__pb2.Message.FromString,
                    response_serializer=validation__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unary.Checks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Checks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChecks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Checks/GetChecks',
            validation__pb2.Message.SerializeToString,
            validation__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
